Working With DB
CyberAsAService/DistributionCenter-BE pull request #18
Opened 2020-08-20 08:32 UTC by Talanger

2020-08-23 19:18 UTC, Talanger commented
ריפרפתי כי היה לי פה הרבה דברים לסגור לפני החופש
ממה שראיתי נראה טוב
@TalShafir תעבור על זה גם בבקשה

2020-08-24 07:56 UTC, TalShafir requested changes

2020-08-24 07:56 UTC, TalShafir commented on src/services/executer/executer-provider.ts
> +export const Executer = async (params: any) => {
Missing more functions/function names
i.e Executor.updateStatus(...)

2020-08-24 07:56 UTC, TalShafir commented on src/services/executer/routes.ts
> +          return "shit";
nice

2020-08-24 07:56 UTC, TalShafir commented on src/services/executer/routes.ts
> +            const data = await controller.Executer(params);
use a more specific function (that needs to be written in the provider)

2020-08-24 07:56 UTC, TalShafir commented on src/services/paas/routes.ts
> +      await db.none(
move to provider

2020-08-24 07:56 UTC, TalShafir commented on src/services/paas/routes.ts
> +        const tasks = (await db.many(`select tasks.id, tasks.command, endpoint_id
move to provider

2020-08-24 07:56 UTC, TalShafir commented on src/services/paas/routes.ts
> +          await db.none(
move to provider

2020-08-24 07:56 UTC, TalShafir commented on src/services/paas/routes.ts
> +        return "shit";
nice

2020-08-24 07:56 UTC, TalShafir commented on src/services/task/routes.ts
> +      const id = await db.one(
move to provider

2020-08-24 07:56 UTC, TalShafir commented on src/services/task/routes.ts
> +      const subtasks = await db.none('INSERT INTO public."Subtasks"( task_id, endpoint_id, status, result) VALUES ( ${task_id}, ${endpoint_id}, ${status}, NULL)', {
move to provider

2020-08-24 07:56 UTC, TalShafir commented on src/services/task/routes.ts
> +        let responsePaaS = await db.oneOrNone(
move to provider

2020-08-24 07:56 UTC, TalShafir commented on src/services/task/routes.ts
> +          await db.none(
move to provider

2020-08-24 09:12 UTC, TalShafir commented on src/services/paas/routes.ts
> +        return "shit";
fixed in another PR

2020-08-27 08:36 UTC, merged